get_gps_server_rails/config/routes.rb
Rails.application.routes.draw do
  resources :vehicle_types

end

get_gps_server_rails/app/models/vehicle_type.rb
class VehicleType < ActiveRecord::Base
end

get_gps_server_rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

get_gps_server_rails/app/controllers/vehicle_types_controller.rb
class VehicleTypesController < ApplicationController
  before_action :set_vehicle_type, only: [:show, :edit, :update, :destroy]

  # GET /vehicle_types
  # GET /vehicle_types.json
  def index
    @vehicle_types = VehicleType.all
  end

  # GET /vehicle_types/1
  # GET /vehicle_types/1.json
  def show
  end

  # GET /vehicle_types/new
  def new
    @vehicle_type = VehicleType.new
  end

  # GET /vehicle_types/1/edit
  def edit
  end

  # POST /vehicle_types
  # POST /vehicle_types.json
  def create
    @vehicle_type = VehicleType.new(vehicle_type_params)

    respond_to do |format|
      if @vehicle_type.save
        format.html { redirect_to @vehicle_type, notice: 'Vehicle type was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle_type }
      else
        format.html { render :new }
        format.json { render json: @vehicle_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicle_types/1
  # PATCH/PUT /vehicle_types/1.json
  def update
    respond_to do |format|
      if @vehicle_type.update(vehicle_type_params)
        format.html { redirect_to @vehicle_type, notice: 'Vehicle type was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle_type }
      else
        format.html { render :edit }
        format.json { render json: @vehicle_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicle_types/1
  # DELETE /vehicle_types/1.json
  def destroy
    @vehicle_type.destroy
    respond_to do |format|
      format.html { redirect_to vehicle_types_url, notice: 'Vehicle type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle_type
      @vehicle_type = VehicleType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_type_params
      params.require(:vehicle_type).permit(:name)
    end
end

get_gps_server_rails/app/helpers/application_helper.rb
module ApplicationHelper
end

get_gps_server_rails/app/helpers/vehicle_types_helper.rb
module VehicleTypesHelper
end

get_gps_server_rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GetGpsServerRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

get_gps_server_rails/app/views/vehicle_types/_form.html.erb
<%= form_for(@vehicle_type) do |f| %>
  <% if @vehicle_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vehicle_type.errors.count, "error") %> prohibited this vehicle_type from being saved:</h2>

      <ul>
      <% @vehicle_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

get_gps_server_rails/app/views/vehicle_types/edit.html.erb
<h1>Editing Vehicle Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @vehicle_type %> |
<%= link_to 'Back', vehicle_types_path %>

get_gps_server_rails/app/views/vehicle_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Vehicle Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vehicle_types.each do |vehicle_type| %>
      <tr>
        <td><%= vehicle_type.name %></td>
        <td><%= link_to 'Show', vehicle_type %></td>
        <td><%= link_to 'Edit', edit_vehicle_type_path(vehicle_type) %></td>
        <td><%= link_to 'Destroy', vehicle_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vehicle type', new_vehicle_type_path %>

get_gps_server_rails/app/views/vehicle_types/new.html.erb
<h1>New Vehicle Type</h1>

<%= render 'form' %>

<%= link_to 'Back', vehicle_types_path %>

get_gps_server_rails/app/views/vehicle_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @vehicle_type.name %>
</p>

<%= link_to 'Edit', edit_vehicle_type_path(@vehicle_type) %> |
<%= link_to 'Back', vehicle_types_path %>